site_name: ChameleonCloud Ops Guide
site_dir: public
site_url: https://chameleoncloud.github.io/operator-docs/
repo_url: https://github.com/ChameleonCloud/operator-docs/
edit_uri: edit/main/docs/

plugins:
  - search
  - mermaid2

theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.sections
    - navigation.expand

nav:
  - Readme: README.md
  - Ticketmaster: ticketmaster.md
  - 'To Sort': guides/catchall.md
  - Guides:
    - 'Change BIOS Settings': guides/bios-changes.md
    - 'Troubleshooting': guides/troubleshooting.md
    - 'Identity Federation': guides/identity_federation.md
    - 'CHI@Edge': guides/chi_edge.md
